#@<> Dba: validating members
validate_members(dba, [
    'check_instance_configuration',
    'configure_instance',
    'configure_local_instance',
    'configure_replica_set_instance',
    'create_cluster',
    'create_replica_set',
    'delete_sandbox_instance',
    'deploy_sandbox_instance',
    'drop_metadata_schema',
    'get_cluster',
    'get_replica_set',
    'help',
    'kill_sandbox_instance',
    'reboot_cluster_from_complete_outage',
    'start_sandbox_instance',
    'stop_sandbox_instance',
    'upgrade_metadata',
    'verbose',
    ])
