session.sql('use sakila;').execute()
session.sql('DROP PROCEDURE IF EXISTS my_procedure;').execute()
session.sql("delimiter // ").execute()
session.sql("create procedure my_procedure (INOUT incr_param INT) BEGIN SET incr_param = incr_param + 1 ; END//  ").execute()
session.sql("delimiter ; ").execute()
session.sql("select name from mysql.proc ;").execute()
session.sql("select name from mysql.proc where name like 'my_procedure';").execute()
session.sql('DROP PROCEDURE IF EXISTS my_procedure;').execute()
session.sql("select name from mysql.proc where name like 'my_procedure';").execute()