
		    // If the _id is provided, it will be honored
		    var result = myColl.add( { _id: 'custom_id', a : 1 } ).execute();
		    print("User Provided Id:", result.getLastDocumentId());

		    // If the _id is not provided, one will be automatically assigned
		    result = myColl.add( { b: 2 } ).execute();
		    print("Autogenerated Id:", result.getLastDocumentId());
	    