
//@# Unsupported server version (should fail)
||Dba.createReplicaSet: An open session is required to perform this operation. (RuntimeError)
||Dba.getReplicaSet: An open session is required to perform this operation. (RuntimeError)
||Dba.configureReplicaSetInstance: An open session is required to perform this operation. (RuntimeError)
||Dba.createReplicaSet: Unsupported server version: This AdminAPI operation requires MySQL version 8.0 or newer, but target is 5.7.[[*]] (RuntimeError)
||Dba.getReplicaSet: Unsupported server version: This AdminAPI operation requires MySQL version 8.0 or newer, but target is 5.7.[[*]] (RuntimeError)
||Dba.configureReplicaSetInstance: Unsupported server version: This AdminAPI operation requires MySQL version 8.0 or newer, but target is 5.7.[[*]] (RuntimeError)
||Dba.createReplicaSet: An open session is required to perform this operation. (RuntimeError)
||Dba.getReplicaSet: An open session is required to perform this operation. (RuntimeError)
||Dba.configureReplicaSetInstance: An open session is required to perform this operation. (RuntimeError)