# If the _id is provided, it will be honored
result = myColl.add( { '_id': 'custom_id', 'a' : 1 } ).execute()
document = myColl.find('a = 1').execute().fetch_one()
print "User Provided Id: %s" % document._id

# If the _id is not provided, one will be automatically assigned
result = myColl.add( { 'b': 2 } ).execute()
document = myColl.find('b = 2').execute().fetch_one()
print "Autogenerated Id: %s" % document._id
