#!/usr/bin/python

import subprocess
from threading import Thread
import Queue

num_workers=4

def test_worker(queue, port):
    while True:
        item = queue.get()
        if item is None:
            break

        print "REBUILD", item
        if "#" in item:
            item = item.split("#")[0]
        subprocess.call(["../unittest/traces/rebuild_traces", item, "--base-sandbox-port=%i"%port])

tasks=subprocess.check_output(["../unittest/traces/rebuild_traces", "--list"]).split()

workers=[]
queue=Queue.Queue()
for i in range(num_workers):
    t = Thread(target=test_worker, args=(queue, 4000 + i*100))
    workers.append(t)
    t.start()

# feed tasks
for t in tasks:
    queue.put(t)

# wait threads to finish
for w in workers:
    queue.put(None)

for w in workers:
    w.join()
