#@ mysqlx type constants
|Type.BIT: <Type.BIT>|
|Type.TINYINT: <Type.TINYINT>|
|Type.SMALLINT: <Type.SMALLINT>|
|Type.MEDIUMINT: <Type.MEDIUMINT>|
|Type.INT: <Type.INT>|
|Type.BIGINT: <Type.BIGINT>|
|Type.FLOAT: <Type.FLOAT>|
|Type.DECIMAL: <Type.DECIMAL>|
|Type.DOUBLE: <Type.DOUBLE>|
|Type.JSON: <Type.JSON>|
|Type.STRING: <Type.STRING>|
|Type.BYTES: <Type.BYTES>|
|Type.TIME: <Type.TIME>|
|Type.DATE: <Type.DATE>|
|Type.DATETIME: <Type.DATETIME>|
|Type.SET: <Type.SET>|
|Type.ENUM: <Type.ENUM>|
|Type.GEOMETRY: <Type.GEOMETRY>|
|Type.SET: <Type.SET>|
